### ISSUE TITLE
Failed Source Build on Apple Silicon

### ISSUE THREAD

**Issue by jhkonan** [hynek/argon2-cffi#68]
I am attempting to build argon2-cffi from source using the provided documentation. I believe the steps are as follows...

```
git clone git@github.com:hynek/argon2_cffi.git
git submodule init
git submodule update
python setup.py build 
pip install -e '.[dev]'
```

However, I run into the following error. Is there anything I can do to fix this issue? Is there a dependency that I am missing?

```
(base) username@User-Mac argon2-cffi % pip install --no-cache-dir -e '.[dev]'
Obtaining file:///Users/username/argon2-cffi
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/username/miniforge3/bin/python3.8 /Users/username/miniforge3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/tmp6azc3l7x
         cwd: /Users/username/argon2-cffi
    Complete output (38 lines):
    Traceback (most recent call last):
      File "/Users/username/miniforge3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/username/miniforge3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/username/miniforge3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 365, in <module>
        setup(
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/username/miniforge3/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 423, in __init__
        _Distribution.__init__(self, {
      File "/Users/username/miniforge3/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/argon2/_ffi_build.py", line 28, in <module>
        ffi = FFI()
      File "/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 2): no suitable image found.  Did find:
    	/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so: mach-o, but wrong architecture
    	/private/var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/pip-build-env-vmy8hdop/overlay/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so: mach-o, but wrong architecture
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/username/miniforge3/bin/python3.8 /Users/username/miniforge3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/cl/8z0j1d3d70j98_bxh5x60z_80000gn/T/tmp6azc3l7x Check the logs for full command output.
```
Thank you for your help.

**Comment by hynek** [comment]
That looks like an error coming CFFI to me. 

I’ve done some casual Googling and it seems like the newer versions of CFFI have some fixes specifically for new macOS versions and ARM. Could you please verify you’re on the latest version `pip freeze | grep cffi`?

**Comment by jhkonan** [comment]
I am using macOS with ARM. For `pip freeze | grep cffi` I get...
```
cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1602537221538/work
```
Should I install cffi from source?

**Comment by hynek** [comment]
Unfortunately I know nothing about conda...try running `python -c 'import cffi; print(cffi.__version__)'`

**Comment by jhkonan** [comment]
Thanks for the code snippets. I get 1.14.3 for the version number, which should be the latest version of cffi. Do you think I should I report this issue on the cffi repo?

**Comment by hynek** [comment]
I _think_ so? I really wouldn't know how to debug this and since I have not access to a DTK (congrats!) there's no way for me to test it. :(

Please link the issue here once you open it!

**Comment by jhkonan** [comment]
It's worth a shot -- thanks! argon2-cffi is a dependency of Jupyter Notebook, so solving this issue would help enable that development environment on Apple silicon.

Here's a link to the issue on CFFI: https://foss.heptapod.net/pypy/cffi/-/issues/477

**Comment by hynek** [comment]
Thank you, let's hope they can help us to figure it out! 🤞

**Comment by hynek** [comment]
To isolate the problem, could you try to build it with stock Python tools and no conda stuff whatsoever please?

**Comment by hynek** [comment]
This is fixed by the outsourcing to https://github.com/hynek/argon2-cffi-bindings

Feel free to try to pip-install argon2-cffi-bindings and report back if it's still broken.
